### ISSUE TITLE
does not allow install on 0.7.10

### ISSUE THREAD

**Issue by deraviin** [scottburton11/burger-time#1]
Maybe this is on purpose but even though this module lists compatibility with 0.7.10 it is not actually able to be installed on foundry instances running that version.
![51d196aea4ffac4a2b155512317546d7](https://user-images.githubusercontent.com/46595619/120136345-5bd37180-c18f-11eb-8c3a-e3a55e5a4e9e.png)

**Comment by scottburton11** [comment]
Apologies, I mixed up the release URL. If you try again, you should get 0.1.5 which installed cleanly on my 0.7.10 instance. 

Thanks @deraviin ! 🙏
