### ISSUE TITLE
Error on loading - via console log

### ISSUE THREAD

**Issue by Jonwh25** [scottburton11/burger-time#4]
Seeing this error when loading up my game. 

![image](https://user-images.githubusercontent.com/60674327/123381398-8a056080-d545-11eb-9040-61ccc369395f.png)

**Comment by scottburton11** [comment]
Thank you for the report @Jonwh25  - the latest release (0.1.7) _may_ have fixed this issue

**Comment by Jonwh25** [comment]
@scottburton11 Thank you. Looks like it is fixed.  Closing this out.
